blank_issues_enabled: false
contact_links:
  - name: 🚀 Getting Started Guide
    url: https://github.com/Aravinda-HWK/Silver-IMAP/blob/main/README.md
    about: Read this first if you're new to Silver-IMAP
  - name: 📖 Documentation
    url: https://github.com/Aravinda-HWK/Silver-IMAP/wiki
    about: Check the documentation for detailed information
  - name: 💬 Discussions
    url: https://github.com/Aravinda-HWK/Silver-IMAP/discussions
    about: Ask questions and discuss ideas with the community_issues_enabled: false