name: CI Tests

permissions:
  contents: read

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - .github/workflows/**
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: go test -v ./...
