name: CI Tests

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - .github/workflows/**

jobs:
  test-commands:
    name: Run Specific Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: make deps

      - name: Test CAPABILITY command
        run: go test -tags=test -v ./test/server -run "TestCapabilityCommand"

      - name: Test NOOP command
        run: go test -tags=test -v ./test/server -run "TestNoopCommand"

      - name: Test LOGOUT command
        run: go test -tags=test -v ./test/server -run "TestLogoutCommand"

      - name: Test APPEND command
        run: go test -tags=test -v ./test/server -run "TestAppendCommand"

      - name: Test AUTHENTICATE command
        run: go test -tags=test -v ./test/server -run "TestAuthenticate"

      - name: Test LOGIN command
        run: go test -tags=test -v ./test/server -run "TestLoginCommand"

      - name: Test STARTTLS command
        run: go test -tags=test -v ./test/server -run "TestStartTLS"

      - name: Test SELECT command
        run: go test -tags=test -v ./test/server -run "TestSelectCommand"

      - name: Test EXAMINE command
        run: go test -tags=test -v ./test/server -run "TestExamineCommand"

      - name: Test CREATE command
        run: go test -tags=test -v ./test/server -run "TestCreateCommand"
