name: Publish Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [published]

# ✅ Explicit top-level permissions set to read-only
permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          VERSION=${{ github.sha }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .

      # Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          VERSION=${{ github.sha }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION